### ISSUE TITLE
time_24hr option is not applied

### ISSUE THREAD

**Issue by adrienpoly** [adrienpoly/stimulus-flatpickr#11]
as discussed in the issue #9 the time_24hr option is not applied.
```erb
<%= f.text_field :start_at,
    data: {
      controller: "flatpickr",
      flatpickr_time_24hr: true,
    } %>
``` 
gets converted to `data-flatpickr-time-24hr` in the html

in the controller the function `kebabCase()` is called to convert `time_24hr`which return `time_24hr` and not `time-24hr` therefore the option is not applied.

### solution
change the `kebabCase()` function to replace `_`by `-`

**Comment by seanfcarroll** [comment]
Thanks @adrienpoly I'll have a go at this tomorrow.

**Comment by adrienpoly** [comment]
@seanfcarroll  As I was working on setting up the test suite I created the test to reproduce the bug and corrected it. Will publish a new version within the day

**Comment by adrienpoly** [comment]
I have just released 1.0.0.beta1 on [npm](https://www.npmjs.com/package/stimulus-flatpickr)

time to 

`yarn upgrade stimulus-flatpickr@beta`

or 

`yarn add stimulus-flatpickr@beta`

Will keep on adding test to `1.0.0` no breaking change expected

**Comment by adrienpoly** [comment]
@seanfcarroll official [v1.0.0](https://www.npmjs.com/package/stimulus-flatpickr/v/1.0.0) is out 🎉

**Comment by seanfcarroll** [comment]
That's awesome @adrienpoly !
