### ISSUE TITLE
A way to pass a list of disabled days of week

### ISSUE THREAD

**Issue by bobmaerten** [adrienpoly/stimulus-flatpickr#21]
Hey there. I had a case when I needed to disable Sundays on my calendar. Flatpickr handle this through a function passed to `disabled` configuration option.

Passing a function within data-attributes is not very convenient so I handled the case by passing a list of days to disable and override the initializer:

```html
input data-controller="flatpickr" data-flatpickr-disabled-days-of-week="[0]"
```

```javascript
initialize() {
  const disabled_days = this.element.dataset.flatpickrDisabledDaysOfWeek
  this.config = {}
  if (disabled_days)
    this.config.disable = [
      function(date) {
        return disabled_days.includes(date.getDay())
      }
    ]
}
```
 
I thing this pattern is rather common, but I'm not really sure on how of if it should be handled with a stimulus-flatpickr specific option.

Hope this helps.

**Comment by adrienpoly** [comment]
available in version `1.1.0-beta1`
https://www.npmjs.com/package/stimulus-flatpickr/v/1.1.0-beta1

`yarn upgrade stimulus-flatpickr@beta`
