### ISSUE TITLE
Exact argument format

### ISSUE THREAD

**Issue by tabuna** [adrienpoly/stimulus-flatpickr#27]
Hi, I have some difficulties with specifying parameters.

For example:

```html
 <input data-controller="flatpickr" data-flatpickr-enable-time="true"
```
it work.

```html
 <input data-controller="flatpickr" data-flatpickr-enable-time="1"
```

not work.

Can we do something about this?

**Comment by adrienpoly** [comment]
yes currently it is expected to have "true" "false" in the next version I will add support for `1`& `0`

**Comment by adrienpoly** [comment]
0/1 are now supported from [version 1.1.1](https://www.npmjs.com/package/stimulus-flatpickr/v/1.1.1)
