### ISSUE TITLE
Multiple dates are not selected by default in edit form

### ISSUE THREAD

**Issue by varmad** [adrienpoly/stimulus-flatpickr#29]
Dear @adrienpoly, 

I am using this plugin in my new project, I have a problem with multiple dates highlight in the edit form. The `defaultDate` data attribute is not working. Could you please help me with this.

Here am attaching the screenshot.

![multiple_dates](https://user-images.githubusercontent.com/3105491/60106436-d6650c80-9782-11e9-9a27-24b2048bff4c.png)

Regards,
Varma

**Comment by adrienpoly** [comment]
hello @varmad 

I had a quick look into it, `defaultDate` is a string in flatpickr. So maybe you could try to pass a string with the multiple dates rather than an array?


Adrien

**Comment by varmad** [comment]
Hello @adrienpoly 

Yes, now it's working. Thank you so much for your quick reply.

I have noticed one more thing while selecting multiple dates from the date picker, by default comma and whitespace(`", "`) are added between the dates, so in edit form also you should populate the dates with the same format.

**Example:** 
_Create form:_  
`2019-06-02, 2019-06-03, 2019-06-04`(format from the calendar)

_Edit form:_
`2019-06-02,2019-06-03,2019-06-04` (this format won't work)
`2019-06-02, 2019-06-03, 2019-06-04` (this will work)

Varma

**Comment by adrienpoly** [comment]
ok thanks for reporting it. I do plan to update this plugin shortly will look into this at that time
