### ISSUE TITLE
A note of support

### ISSUE THREAD

**Issue by chmln** [adrienpoly/stimulus-flatpickr#3]
Hey, thanks for porting flatpickr to stimulus!

If you ever need support from the upstream, don't hesitate to open up an issue at https://github.com/flatpickr/flatpickr.

:+1:

**Comment by adrienpoly** [comment]
Thanks, @chmln so fare so good. On my side, it is working perfectly. The Wrapper is not that complex. I'll try to add a few goodies in the future. 
There are not yet many wrappers in the Stimulus world, I have done it as an experiment to show some folks, alternatives way to add Flatpickr in a Rails app. Hopefully it will help.

Congrats on your job for Flatpickr, love it 👏
