### ISSUE TITLE
Roadmap for the project

### ISSUE THREAD

**Issue by abhinaykumar** [adrienpoly/stimulus-flatpickr#57]
Hi @adrienpoly, I have been using this library for some of the personal projects and I really like how seamlessly it integrates with Stimulus. I was wondering if you have any roadmap for this project so that people can pick and start working towards it?

**Comment by adrienpoly** [comment]
I don't have any formal roadmap yet. Recently I have been spending most of my open source time on Stimulus-Use https://github.com/stimulus-use/stimulus-use

I put quickly a few ideas here https://github.com/adrienpoly/stimulus-flatpickr/projects/1. 
The main roadmap I see is to fully embrace the [Stimulus Value API](https://github.com/stimulusjs/stimulus/pull/202) and the upcoming Stimulus V2

and also there is #45 to reproduce and correct
