### ISSUE TITLE
Uncaught ReferenceError: StimulusFlatpickr is not defined

### ISSUE THREAD

**Issue by daltonrenaldo** [adrienpoly/stimulus-flatpickr#63]
When using the umd build, `StimulusFlatpickr` isn't defined

**Comment by adrienpoly** [comment]
Yeah looking at the build settings it looks like the UMD name would be `stimulus-flatpickr` and I agree that this is not really usual....

https://github.com/adrienpoly/stimulus-flatpickr/blob/master/rollup.config.js#L24-L31

Will update the rollup config to have the name correctly set to `StimulusFlatpickr`
