### ISSUE TITLE
Support Stimulus 3

### ISSUE THREAD

**Issue by scottbarrow** [adrienpoly/stimulus-flatpickr#83]
The package name has changed to @hotwire/stimulus

ERROR in ./node_modules/stimulus-flatpickr/dist/index.m.js 1:0-36
Module not found: Error: Can't resolve 'stimulus' in '/Users/scott/Code/Ollie/OllieOrder/node_modules/stimulus-flatpickr/dist'

**Comment by adrienpoly** [comment]
You can use the 3.0 beta version https://github.com/adrienpoly/stimulus-flatpickr/releases/tag/v3.0.0-0

**Comment by davidnectarestudio** [comment]
Hello.

It is possible to add a Git `v3.0.0` release tag version? I've problems with Symfony Importmap package manager due to missing JsDeliver exisiteing version (only apperas up to v1.4 available).

Thanks @adrienpoly
