### ISSUE TITLE
Stimulus 3.0 support

### ISSUE THREAD

**Issue by tabuna** [adrienpoly/stimulus-flatpickr#84]
Hi, I am getting the following error when I try to compile:

```
ERROR in ./node_modules/stimulus-flatpickr/dist/index.m.js 1:0-38
Module not found: Error: Can't resolve 'stimulus' in '/Users/tabuna/develop/orchid-project/platform/node_modules/stimulus-flatpickr/dist'
```

This only happens on version 3 of the stimulus package. 
Are there any plans to support this for the new version of the package?

**Comment by adrienpoly** [comment]
Duplicate #83

You can use the 3.0 beta version

**Comment by tabuna** [comment]
Thanks.
