### ISSUE TITLE
@hotwire dependency change?

### ISSUE THREAD

**Issue by aviemet** [adrienpoly/stimulus-flatpickr#86]
Copied from the [stimulus npm page](https://www.npmjs.com/package/stimulus):

Stimulus has moved to @hotwired/stimulus. This package now just depends on that new package and exports everything from it for backwards compatibility.

Would it be ok to change the package dependency for this project to the new one?

**Comment by adrienpoly** [comment]
hello 
yes this has been done and released in 3.0 beta #83

will release the 3.0 official version soon
