### ISSUE TITLE
Getting started on development

### ISSUE THREAD

**Issue by seanfcarroll** [adrienpoly/stimulus-flatpickr#9]
Hi @adrienpoly this is a great package and good to see Stimulus-based packages arriving. We are using it in [crowdAI](https://www.crowdai.org/). 

This is more of a general how-to than a specific bug, I hope that is OK.

I *think* there is a bug around the 24 hour time configuration. In any case I can't make it work on crowdAI. I thought I could debug the package, in the way that one can debug a Rubygem. So far, I've tried this:

1. Forked the repo 
3. Tried to add it from the fork

```
yarn add git+ssh//git@github.com:https://github.com/seanfcarroll/stimulus-flatpickr
```

But in fact this is not ideal. It would be better to be able to work locally on the dev environment.

I was wondering if you might have some ideas on how to develop with a local copy of the package?

**Comment by seanfcarroll** [comment]
Hi @adrienpoly thanks for the very informative answer. I will try it out and see if I can isolate the issue, the basic problem is the ```flatpickr_time_24hr: true``` setting seems to be ignored. I notice it is slightly irregular due to it being a ```time_24``` camelcase, and perhaps there is something there.

https://github.com/crowdAI/crowdai/blob/master/app/views/challenges/form/_challenge_round_fields.html.erb#L75-L79

In any case I will follow your instructions, and maybe do a PR (unless the problem is at my end). I'm happy to also do a PR with these instructions if helpful. Cheers

**Comment by adrienpoly** [comment]
you are probably right about the camelcase issue

as a temp fix you can also set it as a default value for all your datepicker in your controller like this

```js 
connect() {
   //global options
    this.config = {
      enableTime: true,
      time_24hr: true
    };
    //always call super.connect()
    super.connect();
  }
```

This is nice for global options so that you don't need to pass them everytime you create a date field in your rails app

**Comment by adrienpoly** [comment]
I have started to add a little test example built with parcel bundler if you want to try it see this #10.
need to document it. a bit in a rush now will work on it later today/tomorrow

**Comment by adrienpoly** [comment]
time_24hr issue is now tracked here #11
